runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /auth/(.*)$
    static_files: dist/facer/index.html
    upload: dist/facer/index.html

  - url: /main/(.*)$
    static_files: dist/facer/index.html
    upload: dist/facer/index.html

  - url: /
    static_files: dist/facer/index.html
    upload: dist/facer/index.html

  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/facer/\1
    upload: dist/facer/(.*)(|\.map)

  - url: /(.*\.(json))$
    static_files: dist/facer/\1
    upload: dist/facer/.*\.(json)$

skip_files:
  - ^node_modules$
  - ^app\.yaml
  - ^README\..*
  - \.gitignore
  - ^\.git$
  - ^grunt\.js
  - ^src$
  - ^e2e$
  - \.editorconfig
  - ^karma\.config\.js
  - ^package\.json
  - ^protractor\.conf\.js
  - ^tslint\.json
